//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vokzal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDocuments
    {
        public int DocumentID { get; set; }
        public int EmployeeID { get; set; }
        public string PassportData { get; set; }
        public string PassportIssuedBy { get; set; }
        public System.DateTime PassportIssueDate { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public string MedicalPolicy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
