//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vokzal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public int ScheduleID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string PassengerLastName { get; set; }
        public string PassengerFirstName { get; set; }
        public string PassengerMiddleName { get; set; }
        public string PassportData { get; set; }
        public int TicketCount { get; set; }
        public string DiscountType { get; set; }
        public decimal TicketPrice { get; set; }
    
        public virtual Schedules Schedules { get; set; }
    }
}
