//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vokzal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainCrews
    {
        public int CrewID { get; set; }
        public int TrainID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Trains Trains { get; set; }
    }
}
