//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vokzal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trains
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trains()
        {
            this.Schedules = new HashSet<Schedules>();
            this.TrainCrews = new HashSet<TrainCrews>();
        }
    
        public int TrainID { get; set; }
        public int TrainNumber { get; set; }
        public int ProductionYear { get; set; }
        public int WagonCount { get; set; }
        public int TrainTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedules> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainCrews> TrainCrews { get; set; }
        public virtual TrainTypes TrainTypes { get; set; }
    }
}
